-- prisma/migrations/001_init/migration.sql
--
-- ⚠️ STATUS: hand-authored to match schema.prisma, NOT generated by
-- `prisma migrate dev` and NOT run against a real database (no PostgreSQL
-- server is reachable in this sandbox). Before trusting this in production:
-- run `npx prisma migrate dev --name init` against a real Postgres instance
-- and let Prisma generate + apply its own migration from schema.prisma —
-- that is the authoritative source. This file is provided so you have a
-- working starting point today, not as a replacement for that step.

CREATE TYPE "Role" AS ENUM ('client', 'staff', 'admin');
CREATE TYPE "ClientStatus" AS ENUM ('active', 'suspended', 'pending');
CREATE TYPE "ProjectStatus" AS ENUM ('pending', 'ongoing', 'completed');
CREATE TYPE "BookingStatus" AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE "PaymentStatus" AS ENUM ('paid', 'pending');
CREATE TYPE "TicketStatus" AS ENUM ('open', 'in-progress', 'resolved');
CREATE TYPE "DocumentCategory" AS ENUM ('report', 'water-test', 'contract', 'other');
CREATE TYPE "ChatSender" AS ENUM ('client', 'company');

CREATE TABLE "User" (
    "id" TEXT PRIMARY KEY,
    "role" "Role" NOT NULL,
    "staffRole" TEXT,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "phone" TEXT NOT NULL,
    "address" TEXT,
    "password" TEXT NOT NULL,
    "status" "ClientStatus" NOT NULL DEFAULT 'active',
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "emailVerificationToken" TEXT UNIQUE,
    "emailVerificationTokenExpires" BIGINT,
    "resetToken" TEXT UNIQUE,
    "resetTokenExpires" BIGINT,
    "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
    "lockUntil" BIGINT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "User_role_idx" ON "User"("role");
CREATE INDEX "User_email_idx" ON "User"("email");

CREATE TABLE "Session" (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
    "refreshTokenHash" TEXT NOT NULL UNIQUE,
    "device" TEXT NOT NULL,
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "revoked" BOOLEAN NOT NULL DEFAULT false,
    "revokedAt" TIMESTAMP(3)
);
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_refreshTokenHash_idx" ON "Session"("refreshTokenHash");

CREATE TABLE "Project" (
    "id" TEXT PRIMARY KEY,
    "clientId" TEXT NOT NULL REFERENCES "User"("id"),
    "location" TEXT NOT NULL,
    "status" "ProjectStatus" NOT NULL DEFAULT 'pending',
    "depth" INTEGER NOT NULL DEFAULT 0,
    "totalDepth" INTEGER NOT NULL DEFAULT 60,
    "waterYield" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "soilType" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedEngineerId" TEXT REFERENCES "User"("id"),
    "notes" TEXT,
    "timeline" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "Project_clientId_idx" ON "Project"("clientId");
CREATE INDEX "Project_status_idx" ON "Project"("status");

CREATE TABLE "Booking" (
    "id" TEXT PRIMARY KEY,
    "clientId" TEXT NOT NULL REFERENCES "User"("id"),
    "requestType" TEXT NOT NULL DEFAULT 'drilling',
    "package" TEXT NOT NULL DEFAULT 'standard',
    "drillingLocation" TEXT NOT NULL,
    "areaType" TEXT NOT NULL DEFAULT 'residential',
    "purpose" TEXT NOT NULL DEFAULT 'drinking',
    "paymentPlan" TEXT NOT NULL DEFAULT 'full',
    "status" "BookingStatus" NOT NULL DEFAULT 'pending',
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Booking_clientId_idx" ON "Booking"("clientId");
CREATE INDEX "Booking_status_idx" ON "Booking"("status");

CREATE TABLE "Payment" (
    "id" TEXT PRIMARY KEY,
    "clientId" TEXT NOT NULL REFERENCES "User"("id"),
    "projectId" TEXT REFERENCES "Project"("id"),
    "amount" DECIMAL(12,2) NOT NULL,
    "method" TEXT NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'paid',
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Payment_clientId_idx" ON "Payment"("clientId");
CREATE INDEX "Payment_status_idx" ON "Payment"("status");

CREATE TABLE "Notification" (
    "id" TEXT PRIMARY KEY,
    "userId" TEXT REFERENCES "User"("id"),
    "type" TEXT NOT NULL DEFAULT 'system',
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");

CREATE TABLE "Ticket" (
    "id" TEXT PRIMARY KEY,
    "ticketNumber" TEXT NOT NULL UNIQUE,
    "clientId" TEXT REFERENCES "User"("id"),
    "subject" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'general',
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "status" "TicketStatus" NOT NULL DEFAULT 'open',
    "location" TEXT,
    "replies" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE INDEX "Ticket_clientId_idx" ON "Ticket"("clientId");
CREATE INDEX "Ticket_status_idx" ON "Ticket"("status");

CREATE TABLE "Document" (
    "id" TEXT PRIMARY KEY,
    "clientId" TEXT REFERENCES "User"("id"),
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "storageProvider" TEXT NOT NULL DEFAULT 'local',
    "category" "DocumentCategory" NOT NULL DEFAULT 'other',
    "uploadedBy" TEXT NOT NULL,
    "uploadedByRole" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Document_clientId_idx" ON "Document"("clientId");

CREATE TABLE "ChatMessage" (
    "id" TEXT PRIMARY KEY,
    "clientId" TEXT NOT NULL REFERENCES "User"("id"),
    "sender" "ChatSender" NOT NULL,
    "senderName" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "ChatMessage_clientId_idx" ON "ChatMessage"("clientId");

CREATE TABLE "Equipment" (
    "id" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "lastMaintenance" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Expense" (
    "id" TEXT PRIMARY KEY,
    "category" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "note" TEXT,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Cms" (
    "id" TEXT PRIMARY KEY DEFAULT 'cms_1',
    "heroTitle" TEXT NOT NULL,
    "heroSubtitle" TEXT NOT NULL,
    "contactPhone" TEXT NOT NULL,
    "contactAddress" TEXT NOT NULL,
    "contactHours" TEXT NOT NULL
);

CREATE TABLE "AuditLog" (
    "id" TEXT PRIMARY KEY,
    "actorId" TEXT REFERENCES "User"("id"),
    "actorName" TEXT NOT NULL,
    "actorRole" TEXT,
    "action" TEXT NOT NULL,
    "details" JSONB NOT NULL DEFAULT '{}',
    "ip" TEXT,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");
CREATE INDEX "AuditLog_date_idx" ON "AuditLog"("date");